### ISSUE TITLE
Credit attribution is now a single broken URL in a subfolder

### ISSUE THREAD

**Issue by alkalait** [sentinel-hub/multi-temporal-super-resolution#1]
Hello, and great work on the blog post and putting together a repo with reproducible notebooks!

I have a few minor corrections/suggestions to provide 🙂

- URL typo in source disclaimer `hrnet/README.md`.
- Citations and credit attributions typically reside in the main README, which should include the aforementioned source disclaimer, and a URL to our arxiv paper (which you already have in the blog post).
- It's a common courtesy in open-source and redistributable source code to repeat such disclaimers in the header of each file in the derived repo - specifically, in each file in `hrnet/` (since the disclaimer in the README can be easily missed.

You've already made a clear attribution to [HighRes-net](https://github.com/ElementAI/HighRes-net) on your blog, which sets a good example for other blogs (when unfortunately credit attribution is mostly an afterthought). 

All the best,

Freddie

**Comment by veseln** [comment]
Hello,
 
First of all, we are very thankful for your work and want to give it the full credit it deserves. We found your code very useful and it provided a nice starting point for our activity.  

I have  updated the repository with the suggested changes. Hope this is now OK for you, if not, please let me know and I can make further adjustments. 

All the best,
Nejc

**Comment by alkalait** [comment]
> Hello,
> 
> First of all, we are very thankful for your work and want to give it the full credit it deserves. We found your code very useful and it provided a nice starting point for our activity.
> 
> I have updated the repository with the suggested changes. Hope this is now OK for you, if not, please let me know and I can make further adjustments.
> 
> All the best,
> Nejc

Thank you for the prompt reply. Your edits look good, hence closing this issue :)
